### ISSUE TITLE
Chatlogger

### ISSUE THREAD

**Issue by ghost** [kevinwbaker/Echelon#5]
Chatlogger appears to have a bug when attempting to add tables It will say that there is no table there and the log comes up with:

[2010-08-15 15:44:35]MYSQL ERROR - Code: 1064 - Message: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'ORDER BY msg_time DESC LIMIT 100' at line 2
# Trace:
#0 E:\echelon.7thcavalry.us\beta\lib\plugins\chatlogs\class.php(159): DB_B3->query('SELECT id, msg_...')
#1 E:\echelon.7thcavalry.us\beta\lib\plugins\chatlogs\class.php(176): chatlogs->pageLogic('0')
#2 E:\echelon.7thcavalry.us\beta\plugin.php(30): chatlogs->returnPage('0')
#3 {main}

**Comment by kevinwbaker** [comment]
If table empty statement has been added to the dev version (not pushed to github just yet). Should be fixed
